<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HN3yVqm' shared service.

return $this->privates['.service_locator.HN3yVqm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.pPyP_uR', 'get_ServiceLocator_PPyPURService.php', true],
    'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true],
    'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true],
    'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.XmHQ4St', 'get_ServiceLocator_XmHQ4StService.php', true],
    'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true],
    'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.pPyP_uR', 'get_ServiceLocator_PPyPURService.php', true],
    'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true],
    'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true],
    'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.XmHQ4St', 'get_ServiceLocator_XmHQ4StService.php', true],
    'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.cMhnip9', 'get_ServiceLocator_CMhnip9Service.php', true],
], [
    'App\\Controller\\CategorieController::delete' => '?',
    'App\\Controller\\CategorieController::edit' => '?',
    'App\\Controller\\CategorieController::index' => '?',
    'App\\Controller\\CategorieController::show' => '?',
    'App\\Controller\\ProduitController::delete' => '?',
    'App\\Controller\\ProduitController::edit' => '?',
    'App\\Controller\\ProduitController::index' => '?',
    'App\\Controller\\ProduitController::show' => '?',
    'App\\Controller\\CategorieController:delete' => '?',
    'App\\Controller\\CategorieController:edit' => '?',
    'App\\Controller\\CategorieController:index' => '?',
    'App\\Controller\\CategorieController:show' => '?',
    'App\\Controller\\ProduitController:delete' => '?',
    'App\\Controller\\ProduitController:edit' => '?',
    'App\\Controller\\ProduitController:index' => '?',
    'App\\Controller\\ProduitController:show' => '?',
]);
