<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR3QqpS4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR3QqpS4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR3QqpS4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR3QqpS4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR3QqpS4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R3QqpS4',
    'container.build_id' => '50047166',
    'container.build_time' => 1570551355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR3QqpS4');
